### ISSUE TITLE
CI issues: name of tokens and failure in release job

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-model#14]
The job is failing due to some issue with connecting to the Metanorma account?

https://github.com/lutaml/lutaml-model/actions/runs/9872542676/job/27262921151

Also, as per #13 , the tokens used in the lutaml repositories are `LUTAML_CI_*` instead of `METANORMA_CI_*`.

@CAMOBAP can you please help? Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse please create https://github.com/lutaml/support to keep all `lutaml`-related configs (as we do with relaton)

P.S. I will fix manually this time

**Comment by CAMOBAP** [comment]
hmm it's already used the right secret variables (there is no dependent on metanorma)

`secrets.LUTAML_CI_RUBYGEMS_API_KEY` - works without issues

@ronaldtse because I have no settings access may I ask you to compare permissions between `secrets.LUTAML_CI_RUBYGEMS_API_KEY` and `secrets.METANORMA_CI_RUBYGEMS_API_KEY`?

P.S. The same issue happens for `lutaml`, https://github.com/lutaml/lutaml/actions/runs/9868264958/job/27249996629
But no issues with [`lutaml-xmi`](https://github.com/lutaml/lutaml-xmi), https://github.com/lutaml/lutaml-xmi/blob/main/.github/workflows/release.yml 

Is it possible that `secrets.LUTAML_CI_RUBYGEMS_API_KEY` is not available for some repos?

**Comment by ronaldtse** [comment]
I manually changed the names for this repo. 

Can you create the support repo?

**Comment by ronaldtse** [comment]
The failure right now is not the inability to push gems but something else... not sure.

**Comment by ronaldtse** [comment]
> P.S. The same issue happens for `lutaml`, https://github.com/lutaml/lutaml/actions/runs/9868264958/job/27249996629 But no issues with [`lutaml-xmi`](https://github.com/lutaml/lutaml-xmi), https://github.com/lutaml/lutaml-xmi/blob/main/.github/workflows/release.yml

`lutaml-xmi` is now deprecated as it has been merged into `lutaml`.

> Is it possible that `secrets.LUTAML_CI_RUBYGEMS_API_KEY` is not available for some repos?

Can't be... it's available for all public lutaml repositories.

**Comment by CAMOBAP** [comment]
> I manually changed the names for this repo.
> 
> Can you create the support repo?

Yep, I didn't know that I could)
I will set it up later as part of  https://github.com/lutaml/support/issues/1 task

> Can't be... it's available for all public lutaml repositories.

It's not the first time we faced such issues, and all times were resolved without actions on my side.

can we just recreate a secret? Maybe it's some weird GitHub configuration issue?

**Comment by ronaldtse** [comment]
@CAMOBAP I have already updated the Rubygem API key, if it's working here then it should work in all lutaml repositories.

**Comment by CAMOBAP** [comment]
@ronaldtse Sorry for mistype, there is no issue with `LUTAML_CI_RUBYGEMS_API_KEY` there is a problem with `LUTAML_CI_PAT_TOKEN`. 

Can you compare `LUTAML_CI_PAT_TOKEN` and `METANORMA_CI_PAT_TOKEN`, and confirm that `LUTAML_CI_PAT_TOKEN` set up in the same way as `METANORMA_CI_PAT_TOKEN`?

**Comment by ronaldtse** [comment]
@CAMOBAP you're right, I just regenerated the token. It seems that the previous token was removed by GitHub...

**Comment by CAMOBAP** [comment]
To works now (re-runned last run)

**Comment by ronaldtse** [comment]
Thanks!
